---
title: "Bibliographic Studies"
subtitle: "Reproducible Bibliometric Analysis of Pathology Articles Using PubMed, E-direct, WoS, Google Scholar"
author: "Serdar Balcı, MD, Pathologist"
date: '`r format(Sys.Date())`'
output: 
  html_notebook: 
    code_folding: hide
    fig_caption: yes
    highlight: kate
    number_sections: yes
    theme: cerulean
    toc: yes
    toc_depth: 5
    toc_float: yes
  html_document: 
    code_folding: hide
    df_print: kable
    highlight: kate
    keep_md: yes
    number_sections: yes
    theme: cerulean
    toc: yes
    toc_float: yes
---

# Introduction

It is a very common bibliometric study type to retrospectively analyse the number of peer reviewed articles written from a country to view the amount of contribution made in a specific scientific discipline.

These studies require too much effort, since the data is generally behind paywalls and restrictions.

I have previously contributed to a research to identify the Articles from Turkey Published in Pathology Journals Indexed in International Indexes; which is published here: [Turk Patoloji Derg. 2010, 26(2):107-113 doi: 10.5146/tjpath.2010.01006](http://www.turkjpath.org/summary_en.php3?id=1423) 

This study had required manual investigation of many excel files, which was time consuming; also redoing and updating the data and results require a similar amount of effort.


---

If you want to see the code used in the analysis please click the code button on the right upper corner or throughout the page. 

I would like to hear your feedback: https://goo.gl/forms/YjGZ5DHgtPlR1RnB3

This document will be continiously updated and the last update was on `r Sys.Date()`.

---


# Analysis

---

## Country Based Comparison

To see the analysis comparing number of pathology articles from Turkey, German and Japan see this analysis: [Country Based Comparison](https://sbalci.github.io/pubmed/CountryBasedComparison.html)

---

## Articles per Journals per Country

In this analysis we aimed to compare number articles per journals per country. We tried to identify if articles from a country is published in certain journals: [Articles Per Journals Per Country](https://sbalci.github.io/pubmed/ArticlesPerJournalsPerCountry.html)

## Most Common MeSH Terms and Keywords used in Pathology Articles from Turkey

In this analysis we aimed to identify the common research topics Turkish pathologists are interested. We extracted most common MeSH terms and keywords from PubMed articles using EDirect:
[MeSH Terms Pathology Articles From Turkey](https://sbalci.github.io/pubmed/MeSH_Terms_Pathology_Articles_From_Turkey.html)


---

<!-- ## Journals Published Articles From Turkey   -->

---

<!-- ## SEER Research Per Countries / Who is doing SEER Research? -->

---

<!-- ## Semantic Scholar -->

---

<!-- ## neutrophil lymph ratio -->

---

<!-- ## retracted pathology articles -->

---

<!-- ## correction pathology articles -->


---

<!-- ## p values in pathology articles a text analysis of pubmed articles using regular expression -->


---

<!-- ## ulakbim patoloji TR dizin -->

---

<!-- ## europepmc paketi ile endometriozis analizi -->



---

<!-- CiteSpaceV -->
<!-- CitNetExplorer -->
<!-- CodeForGitHubGist -->
<!-- css -->
<!-- data -->
<!-- docs -->
<!-- e-utilities-lecture-notes -->
<!-- figure -->
<!-- grid-2018-11-14 -->
<!-- images -->
<!-- Neurosurgery-Articles -->
<!-- pdf -->
<!-- Pediatric-Surgery -->
<!-- rsconnect -->
<!-- Videos -->
<!-- VOSviewer -->

<!-- ArticlesPerJournalsPerCountry.nb.html -->
<!-- BibliographicStudies.html -->
<!-- BibliographicStudies.nb.html -->
<!-- CountryBasedComparison.nb.html -->
<!-- endometriosis.nb.html -->
<!-- JournalsPublishedArticlesFromTurkey.nb.html -->
<!-- Making proper trend graphs.htm -->
<!-- MeSH_Terms_Pathology_Articles_From_Turkey.nb.html -->
<!-- p-values-in-Pathology-Articles.nb.html -->
<!-- PathologyArticlesFromTurkeyComparedtoAllPublishedArticles.nb.html -->
<!-- PubMedPackages.nb.html -->
<!-- README.html -->
<!-- Retrieving and Processing PubMed Records via easyPubMed (html).htm -->
<!-- SchedulePubMedAnalysis.nb.html -->
<!-- SchedulePubMedAnalysis2.nb.html -->
<!-- SEERResearchPerCountries.nb.html -->
<!-- SemanticScholar.nb.html -->
<!-- Sources.html -->
<!-- Sources.nb.html -->
<!-- Untitled.nb.html -->






---

# Sources Used For Analysis

Here are the sources used in these analysis: [Sources Used For Analysis](https://sbalci.github.io/pubmed/Sources.html)

---

# Feedback

[Serdar Balcı, MD, Pathologist](https://github.com/sbalci) would like to hear your feedback: https://goo.gl/forms/YjGZ5DHgtPlR1RnB3

This document will be continiously updated and the last update was on `r Sys.Date()`.

---

<script id="dsq-count-scr" src="//https-sbalci-github-io.disqus.com/count.js" async></script>

<div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
/*
var disqus_config = function () {
this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://https-sbalci-github-io.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

---



