---
title: "Pathology Articles From Turkey Compared to All Published Articles"
output: html_notebook
---

# europepmc

https://cran.r-project.org/web/packages/europepmc/index.html

https://cran.r-project.org/web/packages/europepmc/vignettes/evergreenreviewgraphs.html


```{r}
library(europepmc)
```


```{r}
articlesPerTotalArticles <- europepmc::epmc_hits_trend(query = "(AFF:'Turkey') AND ((AFF:'pathology') OR (AFF:'Pathology'))", period = 1980:2017)

articlesPerTotalArticles
```



A trend graph of articles of #pathologist from #Turkey derived from Europe PMC #RStats #europepmc #evergreenreviewgraph #pathology  #research #bibliography


```{r}
library(ggplot2)
ggplot(articlesPerTotalArticles, aes(year, query_hits / all_hits)) + 
  geom_point() + 
  geom_line() +
  xlab("Year published") + 
  ylab("Proportion of Pathology articles \n from Turkey in Europe PMC")
```


---

# PubMed 

## Data retriveal from PubMed using EDirect 

Article PMID downloaded as `txt`.

```{r Search PubMed download PMID, eval=FALSE, include=FALSE}
myTerm <- rstudioapi::terminalCreate(show = FALSE)
rstudioapi::terminalSend(
    myTerm,
    "esearch -db pubmed -query \"(pathology[Affiliation] OR patoloji[Affiliation]) AND (Turkey[Affiliation] OR Türkiye[Affiliation])\" -datetype PDAT -mindate 1800 -maxdate 3000 | \ efetch -format uid > data/pubmed_result_TurkPath_uid.txt \n"
)
Sys.sleep(1)
repeat {
    Sys.sleep(0.1)
    if (rstudioapi::terminalBusy(myTerm) == FALSE) {
        print("Code Executed")
        break
    }
}
```


---


```{r Search local PubMed with downloaded PMID extract data as xml, eval=FALSE, include=FALSE}
myTerm <- rstudioapi::terminalCreate(show = FALSE)
rstudioapi::terminalSend(
    myTerm,
    "cat data/pubmed_result_TurkPath_uid.txt | \ fetch-pubmed -path /Volumes/Agu2018/PubMed > data/pubmed_result_TurkPath.xml \n"
)
Sys.sleep(1)
repeat {
    Sys.sleep(0.1)
    if (rstudioapi::terminalBusy(myTerm) == FALSE) {
        print("Code Executed")
        break
    }
}
```




---



```{r extract doi from xml, message=FALSE, warning=FALSE}
myTerm <- rstudioapi::terminalCreate(show = FALSE)
rstudioapi::terminalSend(
myTerm,
"xtract -input data/pubmed_result_TurkPath.xml -pattern PubmedArticle -block ArticleId -if ArticleId@IdType -equals doi -element ArticleId > data/pubmed_result_TurkPath_doi.txt \n"
)
Sys.sleep(1)
repeat {
Sys.sleep(0.1)
if (rstudioapi::terminalBusy(myTerm) == FALSE) {
print("Code Executed")
break
}
}
```


```{r}
library(tidyverse)
pubmed_result_TurkPath_doi <- read.delim("data/pubmed_result_TurkPath_doi.txt", header = FALSE)
```


```{r}
pubmed_result_TurkPath_doi$V1[grep("^10.", pubmed_result_TurkPath_doi$V1)]

pubmed_result_TurkPath_doi$V2 <- grepl(
  pattern = "^10.",
  x = pubmed_result_TurkPath_doi$V1
)

pubmed_result_TurkPath_doi2 <- pubmed_result_TurkPath_doi %>% 
  filter(pubmed_result_TurkPath_doi$V2 == TRUE) %>% 
  select(V1)

write_csv(pubmed_result_TurkPath_doi2, "data/pubmed_result_TurkPath_doi2.txt", col_names = FALSE)


```


---

# WOS data for VOSviewer


```
(AD=Turkey AND SU=Pathology) OR (CU=Turkey AND SU=Pathology)
Indexes=SCI-EXPANDED, SSCI, A&HCI, CPCI-S, CPCI-SSH, BKCI-S, BKCI-SSH, ESCI Timespan=All years
```


# Hacettepe[Affiliation] AND Pathology[Affiliation] 


```{r Search PubMed download all articles uid, eval=FALSE, include=FALSE}
myTerm <- rstudioapi::terminalCreate(show = FALSE)
rstudioapi::terminalSend(
    myTerm,
    "esearch -db pubmed -query \"hacettepe[Affiliation] AND (pathology[Affiliation] OR patoloji[Affiliation])\" -datetype PDAT -mindate 1800 -maxdate 3000 | \ efetch -format uid > data/pubmed_result_hacettepe_pathology_uid.txt \n"
)
Sys.sleep(1)
repeat {
    Sys.sleep(0.1)
    if (rstudioapi::terminalBusy(myTerm) == FALSE) {
        print("Code Executed")
        break
    }
}

file.info(here::here("data/pubmed_result_hacettepe_pathology_uid.txt"))$ctime
```


```{r Search PubMed download all articles xml, eval=FALSE, include=FALSE}
myTerm <- rstudioapi::terminalCreate(show = FALSE)
rstudioapi::terminalSend(
    myTerm,
    "esearch -db pubmed -query \"hacettepe[Affiliation] AND (pathology[Affiliation] OR patoloji[Affiliation])\" -datetype PDAT -mindate 1800 -maxdate 3000 | \ efetch -format xml > data/pubmed_result_hacettepe_pathology_uid.xml \n"
)
Sys.sleep(1)
repeat {
    Sys.sleep(0.1)
    if (rstudioapi::terminalBusy(myTerm) == FALSE) {
        print("Code Executed")
        break
    }
}

file.info(here::here("data/pubmed_result_hacettepe_pathology_uid.xml"))$ctime
```




```{r extract if pathology and hacettepe in same affiliation, eval=FALSE, include=FALSE}

myTerm <- rstudioapi::terminalCreate(show = FALSE)
rstudioapi::terminalSend(
myTerm,
"xtract -input data/pubmed_result_hacettepe_pathology_uid.xml -pattern PubmedArticle -tab \"|\" -sep \";\" -def \"NA\" -element MedlineCitation/PMID ArticleTitle Journal/ISSN ISOAbbreviation PubDate/Year Affiliation> data/data_hacettepepathology.csv \n"
)
Sys.sleep(1)
repeat {
Sys.sleep(0.1)
if (rstudioapi::terminalBusy(myTerm) == FALSE) {
print("Code Executed")
break
}
}

```


## read extracted data


```{r read data}
library(readr)
data_hacettepePathology <- read_delim(here::here("data/data_hacettepepathology.csv"), 
    "|",
    escape_double = FALSE,
    col_names = FALSE, 
    trim_ws = TRUE)
# View(data_hacettepePathology)

names(data_hacettepePathology) <- c("PMID", "ArticleTitle", "ISSN", "ISOAbbreviation", "PubDate", "Affiliation")

```


```{r separate affiliations}
library(tidyverse)
library(stringr)
str_count(string = data_hacettepePathology$Affiliation, pattern = ";") %>% 
  max()

```


```{r plain affiliation characters, include=FALSE}

# to.plain <- function(s) {
#         # 1 character substitutions
#     old1 <- "çğşıüöÇĞŞİÖÜ"
#     new1 <- "cgsiuocgsiou"
#     s1 <- chartr(old1, new1, s)
#     # 2 character substitutions
#     old2 <- c("œ", "ß", "æ", "ø")
#     new2 <- c("oe", "ss", "ae", "oe")
#     s2 <- s1
#     for(i in seq_along(old2)) s2 <- gsub(old2[i], new2[i], s2, fixed = TRUE)
#     s2
# }

data_hacettepePathology2 <- data_hacettepePathology %>% 
  select(PMID, Affiliation)


# [[:alpha:]]



# data_hacettepePathology2$Affiliation <- data_hacettepePathology2$Affiliation %>%
#     tolower() %>%
#     to.plain()


data_hacettepePathology2 <-  data_hacettepePathology2 %>% 
  separate(col = "Affiliation", sep = ";", into = paste0("Affiliation", 1:6925))


```




```{r}
library(tidyverse)
library(reshape2)

DT.m1 <- melt(data_hacettepePathology2,
              id.vars = c("PMID"),
              measure.vars = paste0("Affiliation", 1:6925))

DT.m2 <- DT.m1 %>%
  filter(!is.na(value))

DT.m2$count <- 1

```


```{r}
DT.m2$hacettepe <-
    grepl(
        pattern = ("[Hh]acettepe"),
        x =
            DT.m2$value
    )

DT.m2$pathology <-
    grepl(
        pattern = ("[Pp]athology|[Pp]atoloji"),
        x =
            DT.m2$value
    )

DT.m2$speach <-
    grepl(
        pattern = ("[Ss]peach|[Ss]peech"),
        x =
            DT.m2$value
    )


```

```{r}
DT.m3 <- DT.m2 %>% 
  filter(hacettepe == TRUE & pathology == TRUE) %>% 
  filter(speach==FALSE)

```

```{r}
final_hacettepePathology <- data_hacettepePathology %>% 
  filter(PMID %in% DT.m3$PMID) %>% 
  select(-c("Affiliation")) %>% 
  left_join(DT.m3, by="PMID") %>% 
  select(c("PMID", "ArticleTitle", "ISSN", "ISOAbbreviation", "PubDate"), Affiliation = value) %>% 
  unique() %>% 
  mutate(PMIDLink = paste0("https://www.ncbi.nlm.nih.gov/pubmed/", PMID, ""))

writexl::write_xlsx(final_hacettepePathology, here::here("data/final_hacettepePathology.xlsx"))

```


```{r}
cat(paste0(final_hacettepePathology$PMID, " OR ")
)
```


```
(hacettepe[Affiliation] AND (pathology[Affiliation] OR patoloji[Affiliation])) NOT (speach[Affiliation] OR speech[Affiliation]) 
```

```
(Turkey[Affiliation] OR Turkiye[Affiliation]) AND ((pathology[Affiliation] OR patoloji[Affiliation]) NOT (speach[Affiliation] OR speech[Affiliation]))
```


```{r}
library(tidyverse)
library(tidylog)
library(mmpipe)
final_hacettepePathology <- data_hacettepePathology %V>% 
  filter(PMID %in% DT.m3$PMID) %V>% 
  select(-c("Affiliation")) %V>%
  left_join(DT.m3, by="PMID") %V>% 
  select(c("PMID", "ArticleTitle", "ISSN", "ISOAbbreviation", "PubDate"), Affiliation = value) %V>%
  unique() %V>% 
  mutate(PMIDLink = paste0("https://www.ncbi.nlm.nih.gov/pubmed/", PMID, ""))


```


