---
title: "scite.ai"
output:
  html_document:
    df_print: paged
---


```{r load library}
library("tidyverse")
library("rjson")
library("magicfor")
```


```{r read DOI}
myDOI <- readr::read_csv(here::here("data/BalciSdoi.txt"), col_names = "DOI", col_types = "c")
```


```{r add api code}
myDOI <- myDOI %>%
  mutate(apitallies = paste0("https://api.scite.ai/tallies/", DOI)) %>%
  mutate(apipapers = paste0("https://api.scite.ai/papers/", DOI)) %>%
  mutate(reportpages = paste0("https://scite.ai/reports/", DOI)) %>%
  rownames_to_column()
```


```{r get json data}
magicfor::magic_for(silent = TRUE)
json_data <- for (i in 1:(dim(myDOI)[1]-1)) {
    json_name <- paste0("Article", myDOI$rowname[i])
    json_data <- rjson::fromJSON(file = myDOI$apitallies[i])
    Sys.sleep(1)
    put(json_name, json_data)
}
jsonDF <- magicfor::magic_result_as_dataframe()
magicfor::magic_free()

jsonDF <- dplyr::bind_rows(jsonDF$json_data, .id = "meta_information")

```



```{r ggplot}
df <- jsonDF %>% 
    filter(total > 0) %>% 
    select(doi,
           contradicting,
           mentioning,
           supporting,
           unclassified
           ) %>% 
    gather(key = feature, value = number, -doi)

library(ggplot2)

ggplot(data = df) +
  aes(x = doi, fill = feature, color = feature, weight = number) +
  geom_bar(position = 'fill') +
  labs(x = 'DOI',
    y = 'Percentage Of Article Citation Features') +
  theme_minimal() +
  coord_flip()
```

