---
title: "Semantic Scholar"
output: html_notebook
---

Open Research Corpus


https://api.semanticscholar.org/

https://labs.semanticscholar.org/corpus/

https://github.com/allenai/citeomatic

https://api.semanticscholar.org

https://github.com/Santosh-Gupta/Research2Vec

http://www.jaist.ac.jp/event/SCIDOCA/2018/files/Semantic-Scholar-SCIDOCA-2018.pdf

https://open.semanticscholar.org

https://www.springernature.com/gp/researchers/scigraph

https://github.com/allenai/science-parse

http://pdffigures2.allenai.org

http://flourishoa.org

http://babel.eigenfactor.org

http://viziometrics.org/about/

https://www.openacademic.ai

http://eigenfactor.org

http://labs.semanticscholar.org/citeomatic/





---









---

Example

This is a subset of the full Semantic Scholar corpus which represents papers crawled from the Web and subjected to a number of filters.



{
  "id": "4cd223df721b722b1c40689caa52932a41fcc223",
  "title": "Knowledge-rich, computer-assisted composition of Chinese couplets",
  "paperAbstract": "Recent research effort in poem composition has focused on the use of automatic language generation...",
  "entities": [
    "Conformance testing",
    "Natural language generation",
    "Natural language processing",
    "Parallel computing",
    "Stochastic grammar",
    "Web application"
  ],
  "s2Url": "https://semanticscholar.org/paper/4cd223df721b722b1c40689caa52932a41fcc223",
  "s2PdfUrl": "",
  "pdfUrls": [
    "https://doi.org/10.1093/llc/fqu052"
  ],
  "authors": [
    {
      "name": "John Lee",
      "ids": [
        "3362353"
      ]
    },
    "..."
  ],
  "inCitations": [
    "c789e333fdbb963883a0b5c96c648bf36b8cd242"
  ],
  "outCitations": [
    "abe213ed63c426a089bdf4329597137751dbb3a0",
    "..."
  ],
  "year": 2016,
  "venue": "DSH",
  "journalName": "DSH",
  "journalVolume": "31",
  "journalPages": "152-163",
  "sources": [
    "DBLP"
  ],
  "doi": "10.1093/llc/fqu052",
  "doiUrl": "https://doi.org/10.1093/llc/fqu052",
  "pmid": ""
}




Attributes

id  string

S2 generated research paper ID.

title  string

Research paper title.

paperAbstract  string

Extracted abstract of the paper.

entities  list

S2 extracted list of relevant entities or topics.

s2Url  string

URL to S2 research paper details page.

s2PdfUrl  string

URL to PDF on S2 if available.

pdfUrls  list

URLs related to this PDF scraped from the web.

authors  list

List of authors with an S2 generated author ID and name.

inCitations  list

List of S2 paperId's which cited this paper.

outCitations  list

List of paperId's which this paper cited.

year  int

Year this paper was published as integer.

venue  string

Extracted venue published.

journalName  string

Name of the journal that published this paper.

journalVolume  string

The volume of the journal where this paper was published.

journalPages  string

The pages of the journal where this paper was published.

sources  list

Identifies papers sourced from DBLP or Medline.

doi  string

Digital Object Identifier registered at doi.org.

doiUrl  string

DOI link for registered objects.

pmid  string

Unique identifier used by PubMed.

