---
title: "WOS"
output: html_notebook
---

# bibliometrix

---

https://cran.r-project.org/web/packages/bibliometrix/vignettes/bibliometrix-vignette.html


---


http://www.bibliometrix.org/


---



https://cran.r-project.org/web/packages/bibliometrix/bibliometrix.pdf

https://www.rdocumentation.org/packages/bibliometrix/versions/1.8/topics/convert2df


---

```
install.packages(“bibliometrix”, dependencies=TRUE) ### installs bibliometrix package and dependencies

library(bibliometrix)   ### load bibliometrix package
## To cite bibliometrix in publications, please use:
## 
## Aria, M. & Cuccurullo, C. (2017) bibliometrix: An R-tool for comprehensive science mapping analysis, Journal of Informetrics, 11(4), pp 959-975, Elsevier.
##                         
## 
## http:\\www.bibliometrix.org
## 
##                         
## To start with the shiny web-interface, please digit:
## biblioshiny()
```

---




```{r}
# NOT RUN {
# An ISI or SCOPUS Export file can be read using \code{\link{readLines}} function:

# largechar <- readLines('filename.txt')

# filename.txt is an ISI or SCOPUS Export file in plain text or bibtex format.
# The file have to be saved without Byte order mark (U+FEFF) at the beginning
# and EoF code at the end of file.
# The original file (exported by ISI or SCOPUS search web site) can be modified
# using an advanced text editor like Notepad++ or Emacs.

# install.packages("bibliometrix", dependencies = TRUE)

library(bibliometrix)

biblio <- readLines('http://www.bibliometrix.org/datasets/bibliometrics_articles.txt')

biblio_df_df <- convert2df(file = biblio, dbsource = "isi", format = "bibtex")

# }
```


```{r}
# biblio1 <- readLines("data/WOS-Turkey-PathologyField/savedrecs-1-500.txt")

# biblio_df1 <- convert2df(file = biblio1, dbsource = "isi", format = "plaintext")

# biblio_df1 <- isi2df(D = biblio1)

```

```
Error in seq.default(iStart, iStop) : 'from' must be a finite number
This error is due to importing tab seperated or bibtex data instead of plaintext data.
For future download bibtex, plaintext and tab seperated file
```

```{r}
saveRDS(biblio_df_df, "data/WOS-Turkey-PathologyField/savedrecs-1-500.rds")
```


```{r}
results <- biblioAnalysis(biblio_df_df, sep = ";")
results
```


```{r eval=FALSE, include=FALSE}
S <- summary(object = results, k = 10, pause = FALSE)
```




```{r}
plot(x = results, k = 10, pause = FALSE)
```



- readFiles: Load a sequence of ISI or SCOPUS Export files into a large... 

https://rdrr.io/cran/bibliometrix/man/readFiles.html

-  convert2df: Convert a Clarivate Analytics WoS, SCOPUS and COCHRANE... 

https://rdrr.io/cran/bibliometrix/man/isibib2df.html
 



# hindexcalculator

https://cran.rstudio.com/web/packages/hindexcalculator/hindexcalculator.pdf


# read.wos.R

https://github.com/alberto-martin/read.wos.R

https://github.com/alberto-martin/read.wos.R/blob/master/report.Rmd

https://zenodo.org/record/1479822#.XEL7QvxS81J
